"""Generate the Markdown architecture reference, Mermaid sources and the QA report from model.py."""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from model import ADRS, FINDINGS, GLOSSARY, MODULES, PROPOSED_DECISIONS, REPO, ROADMAP, TESTRUN  # noqa: E402

OUT = os.path.abspath(os.path.join(HERE, "..", "out"))


def sot():
    L = []
    a = L.append
    a("# Kota Aerospace — Architecture Source of Truth")
    a("")
    a(f"> Generated from `src/model.py` (blueprint v1.0, 2026-10-01). Evidence base: `{REPO['branch']}` @ `{REPO['commit']}`.")
    a("> Edit `model.py`, then run `python src/gen_docs.py` and `python src/build.py`. Do not edit this file by hand —")
    a("> it is regenerated, so definitions never diverge between the PDF and this reference.")
    a("")
    a("Status vocabulary: **VERIFIED** (code + migration + passing test) · **PARTIAL** · **DESIGNED** (spec/ADR, no code) · **PROPOSED** (this blueprint) · **EXTERNAL** (hardware, provider, field or customer validation) · **VERIFY** (claimed, not confirmed) · **SUPERSEDED**.")
    a("")
    a("## 1. System context")
    a("")
    a("Kota Aerospace is a multi-tenant aerospace intelligence, maintenance and compliance platform for four suites — Aircraft, Drone/UAV, Helicopter, eVTOL/AAM — on one shared core.")
    a("")
    a("| Actor / system | Relationship | Status |")
    a("|---|---|---|")
    for r in [("Operators, MRO, compliance teams", "Web app over HTTPS, JWT bearer", "VERIFIED"),
              ("Platform administrators", "Platform control plane (platform:manage)", "VERIFIED"),
              ("Drones / autopilots", "MAVLink via companion computer or ground relay → UDP/TCP listener or HTTP push", "EXTERNAL"),
              ("MQTT brokers", "TLS subscriber in listeners process", "EXTERNAL"),
              ("DJI FlightHub / OEM clouds", "Signed webhooks; credentialed REST polling", "EXTERNAL"),
              ("LLM provider", "Anthropic or OpenAI-compatible via provider abstraction", "EXTERNAL"),
              ("Email / payment providers", "SMTP for verification codes; billing provider (test provider only)", "EXTERNAL")]:
        a(f"| {r[0]} | {r[1]} | {r[2]} |")
    a("")
    a("## 2. Container / runtime topology")
    a("")
    a("| Container | Technology | Command / location | Status |")
    a("|---|---|---|---|")
    for r in [("Web frontend", "Next.js 16.3.5, React 18", "frontend/ · Vercel project 'aerocomply' (reported)", "VERIFIED (code) / VERIFY (hosting)"),
              ("API service", "FastAPI, uvicorn, Python 3.11 image (3.12 required by one test)", "uvicorn app.main:asgi_app", "VERIFIED"),
              ("Worker + scheduler", "PostgreSQL job queue (SKIP LOCKED)", "python -m app.worker --schedule", "VERIFIED"),
              ("Listeners", "UDP/TCP MAVLink, MQTT", "python -m app.listeners", "VERIFIED"),
              ("PostgreSQL 16", "System of record incl. telemetry, audit, jobs", "Neon (reported)", "VERIFIED"),
              ("Object storage", "S3 API (MinIO locally)", "boto3", "VERIFIED"),
              ("Redis", "Optional shared rate-limit backend", "RATE_LIMIT_BACKEND=redis", "PARTIAL"),
              ("Neo4j", "Started by docker-compose, unused", "infra/docker-compose.yml", "SUPERSEDED"),
              ("Message broker", "None by design", "—", "PROPOSED only on measured need")]:
        a(f"| {' | '.join(r)} |")
    a("")
    a("## 3. Module ownership and data ownership")
    a("")
    a("A module is the only writer of its tables; others call its service functions inside the same transaction.")
    a("")
    a("| Id | Module | Area | Responsibilities | Main entities | Interface | Emits | Depends on | Status | Notes |")
    a("|---|---|---|---|---|---|---|---|---|---|")
    for m in MODULES:
        a(f"| {m['id']} | {m['name']} | {m['area']} | {m['resp']} | {m['entities']} | `{m['api']}` | {m['emits']} | {m['deps']} | {m['status']} | {m['note']} |")
    a("")
    a("## 4. Event contracts")
    a("")
    a("Transport: `audit_events` (immutable, DB trigger) as the domain-event log, and `background_jobs` (enqueued in the same transaction) for asynchronous work. No broker. Proposed: ADR-012 adds `event_version`, `correlation_id` and consumer cursors.")
    a("")
    a("| Event (`action` / job type) | Producer | Consumer |")
    a("|---|---|---|")
    for r in [("mission.created · updated · authorized", "mission_service", "readiness, polling consumers"),
              ("finding.created · disposition_added · closed", "finding_service", "evidence intelligence, M7"),
              ("work_order.created · updated · assigned · transitioned", "work_order_service", "TAT, release readiness"),
              ("task.created · updated · completed", "work_order_service", "inspection gate"),
              ("component/battery .installed · .removed", "installation_service", "configuration as-of view"),
              ("inspection.completed · rejected · marked_not_required · reopened", "inspection_service", "release readiness"),
              ("M7 signal lifecycle transitions", "proactive_intelligence_service", "audit"),
              ("acquisition.ingest (job)", "listeners, HTTP async, webhooks", "worker → acquisition_service.ingest"),
              ("acquisition.poll (job)", "scheduler", "worker → OEM poller"),
              ("retention.sweep · billing.dunning (jobs)", "scheduler", "worker")]:
        a(f"| `{r[0]}` | {r[1]} | {r[2]} |")
    a("")
    a("Canonical telemetry contract: `NormalizedTelemetryEvent` (app/schemas/telemetry.py) — source_system, source_event_id, source_asset_id, event_type, event_timestamp, flight?, battery?, readings[] (sensor_code, sensor_type, measurement_type, finite value, unit, component_id, data_quality), raw_metadata.")
    a("")
    a("## 5. Integration boundaries")
    a("")
    a("| Boundary | Mechanism | Guarantees | Status |")
    a("|---|---|---|---|")
    for r in [("MAVLink UDP/TCP", "listener + JobSink", "CIDR allow-list and/or MAVLink-2 signing; CRC_EXTRA; sequence; back-pressure", "VERIFIED (software) / EXTERNAL (RF)"),
              ("HTTP push", "/data-sources/{id}/ingest (sync or async)", "tenant from user; 25 MB cap; Idempotency-Key", "VERIFIED"),
              ("MQTT", "subscriber", "TLS or loopback; topic filter; backoff", "VERIFIED / EXTERNAL broker"),
              ("Generic webhook", "/webhooks/data-sources/{id}", "HMAC over timestamp.body; ±5 min; replay guard; uniform 401", "VERIFIED"),
              ("DJI FlightHub", "/telemetry/dji/webhook", "HMAC; 503 until configured; target tenant entitlement", "VERIFIED / EXTERNAL"),
              ("OEM REST pull", "acquisition.poll job", "https only; public IPs; no redirects; cursor", "VERIFIED / EXTERNAL"),
              ("LLM", "provider abstraction", "tools grounded; safety guard outside model", "EXTERNAL"),
              ("Edge gateway", "gateway_service.py", "in-memory FIFO; tenant bearer token", "PARTIAL")]:
        a(f"| {' | '.join(r)} |")
    a("")
    a("## 6. Trust boundaries")
    a("")
    for t in ["Public → authenticated: JWT (exp + sub required, DB re-check per request), HMAC webhooks, MAVLink-2 signing.",
              "Authenticated → tenant: organization_id from caller or DataSource row only; foreign ids → 404.",
              "Tenant → internal: RBAC permission + router-level entitlement; ownership checks on cross-references. **Gap F3:** async ingestion paths skip entitlement.",
              "Internal → data: parameterised SQL; immutable audit; evidence checksums; secrets via KOTA_SECRET_<ref>.",
              "AI boundary: LISA tools authorised per call; no organisation argument; deterministic airworthiness guard. **Gap F5:** no separate DB role; tool calls not persisted to audit.",
              "Admin control plane: PLATFORM_ADMIN with platform:manage; four-eyes approvals for expansive tenant changes."]:
        a(f"- {t}")
    a("")
    a("## 7. Architecture decisions")
    a("")
    a("| ADR | Title | ADR status | In code | Risk observed | Validation needed |")
    a("|---|---|---|---|---|---|")
    for d in ADRS:
        a(f"| {d['id']} | {d['title']} | {d['status']} | {d['impl']} | {d['risk']} | {d['validate']} |")
    a("")
    a("Proposed (require approval):")
    a("")
    for p in PROPOSED_DECISIONS:
        a(f"- **{p['id']} — {p['title']}.** {p['why']} Reverse if: {p['reverse']}")
    a("")
    a("## 8. Current vs target state")
    a("")
    a("Current = this register's VERIFIED/PARTIAL rows. Target = ADR-011…016 plus the roadmap below. Hosting is reported, not verified.")
    a("")
    for r in ROADMAP:
        a(f"{r['n']}. **{r['title']}** (after: {r['dep']}) — " + "; ".join(r["items"]) + f". Exit gate: {r['gate']}.")
    a("")
    a("## 9. Known gaps")
    a("")
    for f in FINDINGS:
        a(f"- **{f['id']} ({f['sev']}) {f['title']}.** {f['body']} → {f['action']}")
    a("")
    a("## 10. Glossary")
    a("")
    for k, v in GLOSSARY:
        a(f"- **{k}** — {v}")
    a("")
    return "\n".join(L)


MERMAID = {
    "d05_ingestion_sequence.mmd": """sequenceDiagram
    autonumber
    participant G as Drone + gateway
    participant L as Listener / ingest API
    participant J as background_jobs (PostgreSQL)
    participant W as Worker
    participant T as telemetry_service
    participant H as HUMS
    participant M as M7
    G->>L: MAVLink frames (signed) / HTTP batch
    L->>J: enqueue acquisition.ingest (idempotency key)
    W->>J: claim (FOR UPDATE SKIP LOCKED)
    W->>T: process_normalized_event (SAVEPOINT per event)
    T->>T: dedupe · quality gate · asset/tenant map (unknown → QUARANTINED)
    T->>H: readings
    H->>H: features · baseline · limits → exceedance (advisory lock)
    H-->>M: finding + evidence; signal synced on next M7 sync
    alt handler error
        W->>J: retry with backoff → DEAD after max attempts
    end
""",
    "d07_signal_lifecycle.mmd": """stateDiagram-v2
    [*] --> OPEN: M7 sync creates signal (signal_key dedupe)
    OPEN --> ACKNOWLEDGED: human (audited)
    ACKNOWLEDGED --> IN_REVIEW: human (audited)
    IN_REVIEW --> RESOLVED: human + notes (audited)
    OPEN --> DISMISSED: human + reason
    ACKNOWLEDGED --> DISMISSED: human + reason
    RESOLVED --> [*]
    DISMISSED --> [*]
""",
    "d11_access_decision.mmd": """flowchart LR
    O[Organization ACTIVE] --> S[Suite] --> P[Suite plan] --> SUB[Subscription TRIALING/ACTIVE/PAST_DUE] --> F[Effective features + overrides + limits]
    U[User DB-authoritative] --> R[Roles user_roles] --> PE[Permissions] --> RO[Resource ownership]
    F --> D{Final access decision}
    RO --> D
    D -->|both| A[Allow]
    D -->|feature outside suite| E1[403 SUITE_ENTITLEMENT_REQUIRED]
    D -->|not purchased / no permission| E2[403 forbidden]
    D -->|limit| E3[403 usage_limit_exceeded]
""",
    "d09_compliance_flow.mmd": """flowchart LR
    subgraph Source
      RA[Regulatory authority] --> RD[Regulatory document · revision]
    end
    subgraph Interpretation
      RR[Regulatory requirement · type]
      RV[Rule versioning — PROPOSED]
    end
    subgraph Logic
      AR[Applicability rule · condition tree] --> KE[Kleene evaluator] 
      IN[As-of configuration] --> KE
    end
    subgraph Output
      AE[Evaluation · snapshot · trace] --> CO[Obligation] --> CS[Compliance state]
    end
    RD --> RR --> AR
    KE --> AE
    CO --> EV[Evidence] --> HR[Human review] --> AU[Audit]
""",
    "x03_roadmap.mmd": """flowchart LR
    W1[1 Telemetry acquisition] --> W4[4 HUMS→M7→LISA→MRO traceability]
    W2[2 Unified entitlements] --> W3[3 Tenant isolation & security] --> W6[6 Production operations]
    W2 --> W7[7 Bounded agentic workflows]
    W4 --> W7
    W4 --> W8[8 Predictive intelligence]
    W5[5 Compliance & evidence integrity] --> W8
    W7 --> W8
""",
}


def qa(pdf_pages, overflow_note, svgs):
    L = []
    a = L.append
    a("# Kota Aerospace Architecture Document — QA Report")
    a("")
    a(f"Blueprint v1.0 · generated 2026-10-01 · evidence base `{REPO['branch']}` @ `{REPO['commit']}` (commit date {REPO['commit_date']}).")
    a("")
    a("## 1. Repository sources inspected")
    a("")
    for s in [f"Backend: `backend/app` — {REPO['py_files']} Python files, {REPO['api_routers']} routers ({REPO['route_handlers']} handlers, {REPO['mutating_routes']} mutating), {REPO['models']} SQLAlchemy models, services, listeners, worker, scheduler, AI/LISA modules.",
              f"Database: `backend/alembic/versions` — {REPO['migrations']} migrations (0001 → 0070).",
              f"Tests: `backend/tests` — {REPO['test_files']} files; `frontend/tests` (vitest).",
              f"Frontend: `frontend/` — Next.js 16.3.5, {REPO['frontend_pages']} pages, entitlement guard, mock-only route redirects.",
              "Runtime / CI: `backend/Dockerfile`, `infra/docker-compose.yml`, `.github/workflows/ci.yml`, `.vercel/project.json`.",
              f"Documents: `docs/adr` ({REPO['adrs']} ADRs), `docs/ontology`, `docs/*.md`, root-level architecture and milestone reports (gap matrix, release readiness, data acquisition, security, entitlement, suite, LISA, observability, M17 intelligence, M14/H8 reports, domain events).",
              "Working tree had uncommitted line-ending changes on ~390 files; the audit used the committed HEAD (6bd38ce) via a git bundle."]:
        a(f"- {s}")
    a("")
    a("Not inspected: hosted staging/production environments, provider consoles, production data, physical devices.")
    a("")
    a("## 2. Independent verification runs")
    a("")
    a(f"- Backend: `pytest` on Python {TESTRUN['python']} + PostgreSQL 16 → **{TESTRUN['passed']} passed, {TESTRUN['failed']} failed, {TESTRUN['deselected']} deselected** in {TESTRUN['seconds']} s.")
    a(f"  - Failed: `{TESTRUN['failed_test']}` — {TESTRUN['failed_reason']}.")
    a(f"  - {TESTRUN['py311']}.")
    a(f"- Migrations: {TESTRUN['migrations']}.")
    a(f"- Frontend: vitest {TESTRUN['vitest']}; {TESTRUN['tsc']}; ESLint {TESTRUN['eslint']}.")
    a("- Not run: browser harness (needs a running stack and seed), `next build`, real-storage tests, any hardware or provider test.")
    a("")
    a("## 3. Claims verified")
    a("")
    for s in ["Modular monolith: one FastAPI app, three processes (API, worker/scheduler, listeners).",
              "PostgreSQL is the only store of record; job queue uses FOR UPDATE SKIP LOCKED; audit_events immutable by trigger (migration 0002).",
              "No Neo4j driver dependency; knowledge graph and digital twin are derived in PostgreSQL.",
              "Acquisition connectors (MAVLink v1/v2 with CRC_EXTRA, sequence, signing; MQTT; CSV/JSON; DJI and generic HMAC webhooks; OEM polling) converge on telemetry_service.process_normalized_event.",
              "HUMS engines (features, baselines, diagnostics, degradation, prognostics) and per-sensor limits (0070).",
              "M7 signals persisted in proactive_signal_records with audited lifecycle transitions.",
              "LISA: 61 tools; each declares required_permission and required_feature; deterministic airworthiness guard; one write-capable tool (run_assessment).",
              "Entitlements: suite → plan → subscription → overrides → limits, resolved per request; used by REST (require_feature) and LISA (_require_entitlement).",
              "Applicability: Kleene three-valued evaluation with configuration_snapshot and reasoning_trace.",
              "Work-order state machine (DRAFT … CLOSED, ON_HOLD, CANCELLED) with audited transitions.",
              "Evidence files with SHA-256 checksums in S3-compatible storage."]:
        a(f"- ✅ {s}")
    a("")
    a("## 4. Claims not verified (or contradicted)")
    a("")
    for s in ["Neo4j as derived graph (ADR-003, M14 report) — contradicted by code (F1).",
              "Transactional outbox (ADR-003 text) — no outbox table; jobs-in-transaction is the equivalent (F2).",
              "`ai_tool_audit_log` (LISA_ARCHITECTURE narrative) — not found; tool calls are not persisted (F5).",
              "Separate AI database role (ADR-004/005) — not found (F5).",
              "ADR-005 human_decision / final_status / previous_assessment_id lineage — not in schema (F8).",
              "Import-linter enforcement of module boundaries (ADR-001) — not configured.",
              "Redis cluster, TimescaleDB, Cloudflare WAF topology (deployment guide) — target only, flagged by the repo itself.",
              "RPO < 15 min, RTO < 1 h, WORM evidence (backup runbook) — no evidence of drill or bucket policy.",
              "Staging deployments on Vercel / Render / Neon — reported in documents, not inspected.",
              "Historical '2690 passed, 0 failed' — re-run gave 2689 passed, 1 failed (test start-up race) on Python 3.12; CI's Python 3.11 cannot collect one test file.",
              "FINAL_RELEASE_READINESS lists G1 as OPEN (21 routes) while the gap matrix lists it CLOSED (34 routes) — documents disagree."]:
        a(f"- ⚠️ {s}")
    a("")
    a("## 5. New defects found during the audit")
    a("")
    a("- **M7 work-order status filter** (`proactive_intelligence_service.py:74`) uses `AWAITING_PARTS` and `SCHEDULED`, which are not `WorkOrderStatus` values; overdue work orders in PLANNED, ASSIGNED, ON_HOLD or INSPECTION never raise overdue-maintenance signals (F7).")
    a("- **Async ingestion bypasses entitlement and organisation-suspension checks** — `acquisition_service._load_source` and job handlers check only DataSource status (F3).")
    a("- **Edge gateway buffer** is an in-memory `deque(maxlen=…)` and the uplink default token is a placeholder string `kota_edge_bearer_token` (F4).")
    a("- **Test reliability:** `test_supervisor_starts_a_tcp_listener` connects before the listener binds (F9).")
    a("")
    a("No application code, schema, migration, deployment or configuration was changed.")
    a("")
    a("## 6. Diagrams completed")
    a("")
    for s in ["D01 master ecosystem (radial)", "D02 layered architecture", "D03 backend modular monolith", "D04 infrastructure topology (dark)",
              "D05 drone-to-cloud connectivity", "D06 HUMS processing", "D07 intelligence ownership + signal lifecycle", "D08 LISA & agentic AI",
              "D09 compliance & evidence", "D10 MRO & asset lifecycle", "D11 suite/plan/entitlement", "D12 security & trust boundaries",
              "D13 deployment & operations", "D14·1–3 end-to-end scenarios (sequence)", "X01 event architecture", "X02 traceability lineage",
              "X03 roadmap", "X04 connectivity decision tree", "Dependency matrix (HTML heat table)", "Status register (44 capabilities)"]:
        a(f"- {s}")
    a("")
    a("## 7. Diagrams requiring validation")
    a("")
    for s in ["D04 / D13 hosting (Vercel, Render, Neon) — confirm against provider consoles.",
              "D05 physical paths (companion computer, GCS relay, satellite) — confirm on a bench with a real autopilot.",
              "D10 dependency matrix — derived from service imports and reading; confirm with an import graph tool before enforcing.",
              "D12 encryption at rest / backups — confirm provider settings.",
              "ADR-008 engine-as-subject — confirm whether engine-subject evaluations exist."]:
        a(f"- {s}")
    a("")
    a("## 8. Broken or unclear dependencies")
    a("")
    for s in ["M06 → M03 entitlement check missing on async paths.", "M08 reads WorkOrder statuses through string literals instead of model constants.",
              "Two proactive surfaces (/proactive and /intelligence/signals).", "M7 and HUMS write during GET requests (sync-on-read).",
              "'M14' names both a milestone and a service."]:
        a(f"- {s}")
    a("")
    a("## 9. Visual and PDF rendering checks")
    a("")
    a(f"- PDF rendered with Chromium (Playwright), A4 landscape, {pdf_pages} pages, fonts embedded (IBM Plex Sans / Condensed / Mono, Space Grotesk; DejaVu Sans fallback for arrows).")
    a(f"- Every page rendered to PNG (pypdfium2) and inspected visually; overflow check on every page: {overflow_note}.")
    a("- Fixed during QA: clipped zone labels, connectors crossing boxes (D02, D05, D06, D07, D10, X01), misleading one-to-one arrows (D05 buses), badge/title collisions, empty card stretch, roadmap header remnants, sequence labels clipped at the right edge, overflowing tables split or compacted.")
    a("- Vector diagrams are inline SVG (crisp at any zoom). Clickable contents and cross-references are internal PDF links; PDF outline/tagging requested from Chromium.")
    a(f"- {len(svgs)} standalone SVG sources exported.")
    a("")
    a("## 10. Known limitations")
    a("")
    for s in ["Reference images mentioned in the brief were not supplied; visual direction followed the written description.",
              "Smallest diagram labels print at ≈6.5 pt on A4; use the SVG sources for large-format printing.",
              "Some scenario message labels sit close to step numbers on dense rows.",
              "Not a substitute for a penetration test, capacity test or provider validation."]:
        a(f"- {s}")
    a("")
    a("## 11. Recommended follow-up actions")
    a("")
    for s in ["Fix the M7 status filter (one-line change + regression test) — highest value, lowest effort.",
              "Approve or reject ADR-011 (PostgreSQL derived graph) and remove Neo4j from docker-compose.",
              "Add the entitlement re-check to acquisition paths (ADR-013).",
              "Pin Python 3.12 in CI and Dockerfile; add vitest to CI; add a readiness wait to the listener test.",
              "Decide the first supported field connectivity path and run the bench test.",
              "Assign an owner for this blueprint; regenerate it after each milestone."]:
        a(f"- {s}")
    a("")
    return "\n".join(L)


if __name__ == "__main__":
    with open(os.path.join(OUT, "ARCHITECTURE_SOURCE_OF_TRUTH.md"), "w") as fh:
        fh.write(sot())
    os.makedirs(os.path.join(OUT, "mermaid"), exist_ok=True)
    for n, t in MERMAID.items():
        with open(os.path.join(OUT, "mermaid", n), "w") as fh:
            fh.write(t)
    import glob
    svgs = glob.glob(os.path.join(OUT, "svg", "*.svg"))
    pages = int(sys.argv[1]) if len(sys.argv) > 1 else 0
    with open(os.path.join(OUT, "KOTA_AEROSPACE_ARCHITECTURE_DOCUMENT_QA.md"), "w") as fh:
        fh.write(qa(pages, "no page overflows (automated scrollHeight check)", svgs))
    print("ok")
