"""Canonical architecture model for the Kota Aerospace blueprint.

Single source for module ownership, statuses, findings, decisions and roadmap. The PDF,
the architecture reference (ARCHITECTURE_SOURCE_OF_TRUTH.md) and the QA report are all
generated from this file, so a definition is never written twice.

Evidence base: repository `Documents/Aerocomply`, branch `feature/post-freeze-productionization`,
commit 6bd38ce (2026-10-01). Statuses use the vocabulary in svg.STATUS.
"""

REPO = {
    "name": "Aerocomply (Kota Aerospace)",
    "branch": "feature/post-freeze-productionization",
    "commit": "6bd38ce",
    "commit_date": "2026-10-01",
    "commits": 347,
    "first_commit": "2026-08-29",
    "py_files": 346,
    "api_routers": 57,
    "route_handlers": 523,
    "mutating_routes": 252,
    "models": 95,
    "migrations": 70,
    "test_files": 214,
    "frontend_pages": 137,
    "lisa_tools": 61,
    "adrs": 10,
}

# filled from the independent test run in this audit (see QA report)
TESTRUN = {
    "python": "3.12.3",
    "postgres": "16",
    "passed": 2689, "failed": 1, "deselected": 16, "seconds": 651,
    "failed_test": "tests/integration/test_listeners.py::test_supervisor_starts_a_tcp_listener",
    "failed_reason": "ConnectionRefused: the test connects before the supervisor's TCP server task has bound the port (no readiness wait); failed 3/3 re-runs in this environment, reported passing on the developer machine",
    "py311": "tests/integration/test_observability.py fails collection on Python 3.11 (3.12-only f-string syntax) — CI pins 3.11",
    "migrations": "alembic upgrade head on an empty PostgreSQL 16 database: 0001 → 0070, clean",
    "vitest": "37 files / 383 tests passed",
    "tsc": "tsc --noEmit clean (exit 0)",
    "eslint": "0 errors, 129 warnings",
}

# ------------------------------------------------------------------ modules
# id, name, owner area, responsibilities, entities, interfaces, emits, consumes, depends, data, status, code, note
MODULES = [
    dict(id="M01", name="Identity & access", area="Platform core",
         resp="Authentication (JWT + Argon2), DB-authoritative session check, RBAC permission catalogue, enterprise SSO (OIDC / Entra), verification codes.",
         entities="User, UserRole, SSOConfiguration, ExternalIdentityMapping, AuthVerificationCode",
         api="/auth, /sso, /users", emits="user.*, role.* audit events", consumes="—",
         deps="Organization & tenancy", data="users, user_roles, sso_*", status="VERIFIED",
         code="core/security.py, core/deps.py, core/permissions.py, services/auth_service.py, sso_service.py",
         note="SSO code and tests present; production IdP configuration is external."),
    dict(id="M02", name="Organization & tenancy", area="Platform core",
         resp="Tenant lifecycle (active, suspended, deletion-pending, restore), facilities, organisation settings, tenant-scoped base mixin.",
         entities="Organization, Facility, TenantScopedMixin",
         api="/tenant, /facilities", emits="organization.* audit events", consumes="Approval requests",
         deps="Identity & access", data="organizations, facilities", status="VERIFIED",
         code="services/tenant_service.py, facility_service.py, deletion_service.py, restoration_service.py",
         note="Organisation has a single org_type (ADR-007 multi-role table deferred)."),
    dict(id="M03", name="Suite, plan & subscription", area="Commercial",
         resp="Product catalogue (suite → module → page/feature), suite-bound plans, subscriptions, tenant overrides, usage limits, single entitlement resolver, billing abstraction, dunning.",
         entities="ProductSuite, ProductModule, ProductFeature, Plan, PlanFeature, Subscription, TenantEntitlementOverride, Invoice, Payment",
         api="/entitlements, /product-catalog, /commercial-platform, /billing", emits="subscription.*, plan.* audit; billing.dunning job",
         consumes="scheduler", deps="Organization & tenancy", data="product_*, plans, subscriptions, billing_*", status="VERIFIED",
         code="services/entitlement_service.py, plan_service.py, subscription_service.py, billing_service.py, limit_enforcement_service.py",
         note="Real payment provider external; legacy default plan mixes drone + aircraft features (documented gap)."),
    dict(id="M04", name="Asset registry & configuration", area="Shared domain",
         resp="Generic asset registry for all four families, aircraft/drone/helicopter/eVTOL detail tables, components, engines, batteries, installation history, asset resolution for ingestion.",
         entities="Asset, Aircraft, AirframeDetails, Component, InstallationHistory, Battery, ExternalAssetMapping",
         api="/assets, /aircraft, /drones, /airframes, /fleet/components", emits="component.installed/removed, battery.installed/removed",
         consumes="—", deps="Tenancy, Entitlements", data="assets, aircraft, airframe_details, components, installation_history, batteries",
         status="VERIFIED", code="services/asset_service.py, aircraft_service.py, drone_service.py, airframe_service.py, component_service.py, installation_service.py",
         note="Configuration-as-of view (ADR-010) partially realised via evaluation configuration_snapshot."),
    dict(id="M05", name="Fleet operations", area="Shared domain",
         resp="Missions, flights, AOG events and recovery, control center, readiness inputs.",
         entities="Mission, Flight, AogEvent", api="/missions, /aog, /control-center", emits="mission.created/updated/authorized",
         consumes="Telemetry (flights)", deps="Asset registry", data="missions, flights, aog_events", status="VERIFIED",
         code="services/mission_service.py, flight_service.py, aog_service.py, aog_recovery_service.py, control_center_service.py", note=""),
    dict(id="M06", name="Telemetry acquisition & ingestion", area="Data acquisition",
         resp="Data sources, connectors (MAVLink v1/v2, MQTT, CSV/JSON, DJI, generic webhook, OEM pull), listeners, quality gate, asset/tenant mapping, quarantine, persistence, source health.",
         entities="DataSource, TelemetryEventLog, HUMSSensorReading, EdgeDevice, BackgroundJob",
         api="/data-sources/{id}/ingest, /telemetry/*, /webhooks/data-sources/{id}, /edge-hardware/*",
         emits="acquisition.ingest / acquisition.poll jobs; telemetry audit", consumes="listeners, scheduler",
         deps="Asset registry, Entitlements (flight_telemetry)", data="data_sources, telemetry_event_logs, hums_sensor_readings, background_jobs",
         status="VERIFIED", code="services/acquisition_service.py, telemetry_service.py, services/edge/*, listeners/*, api/v1/webhooks.py",
         note="Field validation (radios, brokers, OEM, DJI) external. Edge buffer is in-memory."),
    dict(id="M07", name="HUMS", area="Intelligence",
         resp="Feature extraction, baselines, drift, exceedances, diagnostics (fault signatures), degradation, prognostics/RUL estimate, per-sensor limits, finding + evidence creation.",
         entities="HUMSSensor, HUMSFeature, HUMSBaseline, HUMSExceedance, HUMSDiagnosticCandidate, HUMSPrognosticRecord",
         api="/hums/*", emits="Finding + Evidence rows; HUMS_* signals via M7 sync", consumes="telemetry readings (in-transaction)",
         deps="Telemetry, Asset registry, Inspections (findings), Evidence", data="hums_*", status="VERIFIED",
         code="services/hums/*, hums_service.py, hums_templates.py",
         note="Deterministic. Rotor / eVTOL-specific analytics need OEM data (external)."),
    dict(id="M08", name="Proactive intelligence (M7)", area="Intelligence",
         resp="Canonical owner of actionable signals: maintenance/inspection thresholds, recurring findings, utilisation, compliance-evidence gaps, readiness degradation, HUMS + telemetry-freshness signals; lifecycle (ack, review, resolve, dismiss).",
         entities="ProactiveSignalRecord", api="/intelligence/signals, /intelligence/proactive",
         emits="signal lifecycle audit; kota_m7_signals_total", consumes="HUMS, MRO, compliance, telemetry",
         deps="HUMS, MRO, Compliance, Telemetry", data="proactive_signal_records", status="VERIFIED",
         code="services/intelligence/proactive_intelligence_service.py",
         note="Signals are synced on read (GET triggers writes). Legacy /proactive alerts service still exposed."),
    dict(id="M09", name="Cross-asset analytics (M14-ext) & fleet summary (M4.2)", area="Intelligence",
         resp="Descriptive fleet distributions (health, coverage, freshness, exceedance, diagnostic, prognostic); M4.2 per-asset decision summary; digital twin (derived, PostgreSQL).",
         entities="(read-only views) FleetIntelligenceSummary", api="/intelligence/fleet, /aerospace-intelligence, /digital-twin",
         emits="—", consumes="M7 signals, HUMS rows", deps="M7, HUMS, Asset registry", data="none owned (derived)", status="VERIFIED",
         code="services/intelligence/cross_asset_intelligence_service.py, fleet_intelligence_service.py, digital_twin_service.py, knowledge_graph.py",
         note="Descriptive only; predictive cross-asset models are proposed."),
    dict(id="M10", name="MRO", area="Operations",
         resp="Work orders + tasks, maintenance programme, deferred items, parts, inventory, procurement, purchase orders, receiving, vendors, technicians, TAT, release readiness, MRO intelligence.",
         entities="WorkOrder, Task, MaintenanceRequirement, DeferredItem, Part, InventoryTransaction, PurchaseOrder, Vendor, TechnicianQualification",
         api="/work-orders, /maintenance, /parts, /procurement, /purchase-orders, /receiving, /release-readiness, /tat",
         emits="work_order.*, task.* audit events", consumes="Findings, M7 signals (via user action)",
         deps="Asset registry, Inspections, Evidence", data="work_orders, tasks, parts, purchase_orders, …", status="VERIFIED",
         code="services/work_order_service.py, maintenance_service.py, part_*.py, procurement_service.py, release_readiness_service.py", note=""),
    dict(id="M11", name="Inspections & findings", area="Operations",
         resp="Inspection requirements (incl. RII), findings, dispositions, finding correlation.",
         entities="InspectionRequirement, Finding", api="/inspections, /findings",
         emits="inspection.*, finding.* audit events", consumes="HUMS exceedances", deps="Asset registry, Work orders", data="inspection_requirements, findings",
         status="VERIFIED", code="services/inspection_service.py, finding_service.py", note=""),
    dict(id="M12", name="Compliance & rules engine", area="Compliance",
         resp="Regulatory documents/requirements, deterministic applicability (Kleene three-valued logic), obligations, compliance assessments, assessment engine.",
         entities="RegulatoryDocument, RegulatoryRequirement, ApplicabilityRule, ApplicabilityCondition, ApplicabilityEvaluation, ComplianceObligation, ComplianceAssessment, Assessment",
         api="/regulatory, /applicability, /compliance, /assessments", emits="obligation sync audit", consumes="Asset configuration, Evidence",
         deps="Asset registry, Evidence", data="regulatory_*, applicability_*, compliance_*, assessments", status="PARTIAL",
         code="services/applicability/*, services/compliance/*, compliance_service.py, regulatory_service.py, services/assessment/engine.py",
         note="Rules have no version column; ADR-005 human-decision lineage fields not in schema."),
    dict(id="M13", name="Evidence management", area="Compliance",
         resp="Evidence records and lifecycle (required → accepted/rejected), files in S3-compatible storage with SHA-256 checksums, reconciliation, provenance.",
         entities="Evidence, EvidenceFile", api="/evidence", emits="evidence lifecycle audit", consumes="HUMS, tasks, obligations",
         deps="Object storage", data="evidence, evidence_files, object store", status="VERIFIED",
         code="services/evidence_service.py, evidence_file_service.py, evidence_reconciliation_service.py, services/storage/*",
         note="WORM / object-lock not configured in code (bucket policy is deployment-side)."),
    dict(id="M14", name="LISA & AI orchestration", area="Intelligence",
         resp="Intent and entity resolution, conversation context, tool registry (61 tools), per-call permission → subscription → suite → feature checks, deterministic airworthiness safety guard, provider abstraction.",
         entities="LisaConversationContext, ToolSpec", api="/lisa", emits="tools_invoked in response (not persisted)",
         consumes="All domain services via tools", deps="All read services, Entitlements", data="lisa_conversation_context", status="PARTIAL",
         code="services/ai/*, services/lisa/*",
         note="Tool calls not written to the audit log; answer quality with a real provider is external."),
    dict(id="M15", name="Notifications", area="Platform core",
         resp="Email for verification codes; tenant notification preferences.",
         entities="(settings on tenant)", api="/tenant (preferences)", emits="—", consumes="—",
         deps="Email provider", data="tenant settings", status="PARTIAL",
         code="services/email_service.py",
         note="No signal / work-order notification fan-out yet."),
    dict(id="M16", name="Audit, export & reporting", area="Governance",
         resp="Immutable audit events (DB trigger), tenant export, hypercare; audit log doubles as the domain-event log.",
         entities="AuditEvent", api="/platform/audit, exports", emits="—", consumes="every mutating service",
         deps="—", data="audit_events (append-only)", status="VERIFIED",
         code="services/audit_service.py, export_service.py, hypercare_service.py, migration 0002",
         note="Report pages (/reports) are labelled not-connected (product decision)."),
    dict(id="M17", name="Platform administration", area="Governance",
         resp="Platform control plane: provisioning, customer health, approvals (four-eyes), platform metrics, retention policies.",
         entities="ApprovalRequest, RetentionPolicy", api="/platform/*", emits="platform audit", consumes="—",
         deps="All", data="approval_requests, retention_*", status="VERIFIED",
         code="services/platform_service.py, provisioning_service.py, approval_service.py, retention_service.py", note=""),
    dict(id="X01", name="Jobs, scheduler & workers", area="Runtime",
         resp="Durable PostgreSQL job queue (SKIP LOCKED), retries, dead-letter, stale reclaim, idempotency keys, scheduler for retention, dunning, OEM polls.",
         entities="BackgroundJob", api="python -m app.worker [--schedule]", emits="kota_jobs_total", consumes="enqueue()",
         deps="PostgreSQL", data="background_jobs", status="VERIFIED", code="services/job_service.py, worker.py, scheduler.py", note=""),
]

# ------------------------------------------------------------------ headline findings (architecture corrections)
FINDINGS = [
    dict(id="F1", sev="High", title="Neo4j decision conflict",
         body="ADR-003 (Accepted) and the M14 report describe Neo4j as a derived graph fed by an outbox. The code uses PostgreSQL only (knowledge_graph.py, digital_twin_service.py); neo4j_* settings are unused, yet docker-compose still starts Neo4j. The gap matrix records the change but ADR-003 was never superseded.",
         action="Write ADR-011 superseding ADR-003; remove Neo4j from local compose or mark optional."),
    dict(id="F2", sev="High", title="No transactional outbox / event bus",
         body="Domain events are AuditEvent rows consumed by polling; asynchronous work uses the background_jobs table enqueued inside the request transaction. This is outbox-equivalent for jobs, but there is no versioned event contract, no consumer offsets and no replay tool.",
         action="Formalise audit + jobs as the event backbone (event_version, correlation_id), not a broker."),
    dict(id="F3", sev="High", title="Async ingestion ignores entitlement changes",
         body="Router-level require_feature guards the HTTP surfaces, but job handlers, listeners and OEM polls do not re-resolve entitlements. A tenant whose subscription is cancelled keeps ingesting through an ACTIVE data source until it is paused.",
         action="Check flight_telemetry entitlement in acquisition_service.ingest and the poll scheduler."),
    dict(id="F4", sev="High", title="Store-and-forward is not durable",
         body="The edge gateway buffers in a bounded in-memory deque (oldest dropped on overflow, lost on power cycle), and MAVLink events are stamped with arrival time, so post-flight synchronised data loses its true measurement time.",
         action="Disk-backed queue on the gateway; carry SYSTEM_TIME / GPS epoch and a gateway sequence number."),
    dict(id="F5", sev="Medium", title="AI write boundary is convention, not structure",
         body="ADR-004/005 require a separate DB role for the AI module without write grants. LISA runs in the API's own session; one tool (run_assessment) writes. ADR-001's import-linting is not configured. Tool invocations are returned to the caller but not persisted to the audit log.",
         action="Classify tools read / draft / write; persist every tool call as an AuditEvent; add import-linter contracts."),
    dict(id="F6", sev="Medium", title="Reads that write (signal sync on GET)",
         body="M7 sync_and_get_signals and HUMS get_asset_health_intelligence persist records during GET requests. Correct today (idempotent keys, advisory locks) but couples read latency to write contention and makes the signal authority depend on who reads first.",
         action="Move sync to worker jobs triggered by telemetry / MRO events; keep GET read-only."),
    dict(id="F7", sev="High", title="Signal vocabulary drift (with a live defect)",
         body="/proactive (legacy computed alerts + daily brief) coexists with M7 /intelligence/signals. 'M14' names both the commercialisation milestone and the cross-asset intelligence service; signal_type is a free string(64). Concrete defect: M7's overdue-maintenance rule filters work orders on AWAITING_PARTS / SCHEDULED, which are not WorkOrderStatus values, so PLANNED, ASSIGNED, ON_HOLD and INSPECTION work orders never raise overdue signals (proactive_intelligence_service.py:74).",
         action="Fix the status filter to WorkOrderStatus constants; retire or fold /proactive into M7; registry for signal types."),
    dict(id="F8", sev="Medium", title="Compliance lineage and rule versioning",
         body="Applicability evaluations keep configuration_snapshot and reasoning_trace (good), but rules have no version and the ADR-005 human-decision / final-status / previous-assessment lineage is not in the schema.",
         action="Add rule_version + effective dating; implement ADR-005 decision rows or amend the ADR."),
    dict(id="F9", sev="Medium", title="CI runtime drift",
         body="CI and the Dockerfile pin Python 3.11, but tests/integration/test_observability.py uses 3.12-only f-string syntax and fails collection on 3.11. CI also does not run the frontend vitest suite. In this audit's independent run one listener test failed deterministically (a start-up race in the test).",
         action="Pin Python 3.12 everywhere (or fix the test); add vitest to CI."),
    dict(id="F10", sev="Low", title="Documentation drift",
         body="Several documents describe targets as if built (Redis cluster, TimescaleDB, ai_tool_audit_log, WORM storage, RPO < 15 min). Most now carry status banners; FINAL_RELEASE_READINESS still lists G1 as open while the gap matrix lists it closed.",
         action="Treat this blueprint's status register as the index; banner or archive superseded documents."),
]

# ------------------------------------------------------------------ architecture decisions register
ADRS = [
    dict(id="ADR-001", title="Modular monolith", status="Accepted", impl="VERIFIED",
         problem="Small team, unproven boundaries, AI must never share compliance write paths.",
         choice="One FastAPI deployable; internal modules; boundaries by review + import linting.",
         alts="Microservices; undifferentiated app.", trade="Coarse scaling; discipline required.",
         risk="Boundaries erode: import-linter not configured; module folders ai/, graph/, rules_engine/ are empty stubs while code lives in services/.",
         validate="Add import-linter contracts in CI.", evidence="backend/app (single app), pyproject.toml"),
    dict(id="ADR-002", title="PostgreSQL as source of truth", status="Accepted", impl="VERIFIED",
         problem="Legally defensible traceability for years.", choice="PostgreSQL 16 holds all transactional, tenant, audit data.",
         alts="Neo4j primary; dual-primary.", trade="Graph traversals more verbose in SQL.",
         risk="Telemetry growth in plain tables (no partitioning).", validate="Capacity test; partition hums_sensor_readings by month when needed.",
         evidence="70 Alembic migrations, 95 models"),
    dict(id="ADR-003", title="Neo4j as derived knowledge graph", status="Accepted (on paper)", impl="SUPERSEDED",
         problem="Multi-hop reassessment candidates.", choice="Neo4j projection via outbox, rebuildable.",
         alts="Recursive CTEs in PostgreSQL.", trade="Extra store and sync.",
         risk="Code took the alternative; ADR never updated.", validate="Record ADR-011 (PostgreSQL derived graph) and its reversal condition.",
         evidence="services/knowledge_graph.py (GraphRepository seam), no neo4j driver dependency"),
    dict(id="ADR-004", title="LLM is not the compliance decision engine", status="Accepted", impl="PARTIAL",
         problem="Airworthiness conclusions must be reproducible.", choice="Rules engine decides; AI explains read-only.",
         alts="LLM-as-verifier; LLM + mandatory sign-off.", trade="Rule authoring is human work.",
         risk="Separate AI DB role not implemented; enforcement is application-level + safety regex.",
         validate="DB role or service-layer write guard for LISA; persisted tool audit.", evidence="services/ai/safety.py, tools.py"),
    dict(id="ADR-005", title="Human decision boundary", status="Accepted", impl="PARTIAL",
         problem="One mutable status conflates system, human and final positions.", choice="Immutable lineage: system_result → human_decision → final_status.",
         alts="Mutable status; side table.", trade="More rows.",
         risk="applicability_evaluations has system_result + snapshot but no human_decision / final_status / previous id.",
         validate="Implement decision rows or amend the ADR to the evidence-review + approval model actually built.",
         evidence="models/applicability.py, approval_request.py (four-eyes)"),
    dict(id="ADR-006", title="Regulatory requirement as core abstraction", status="Accepted", impl="VERIFIED",
         problem="AD, SB, AMC… share one shape.", choice="RegulatoryRequirement + type discriminator.", alts="Table per type; EAV.",
         trade="Type filters in queries.", risk="—", validate="—", evidence="models/compliance.py"),
    dict(id="ADR-007", title="Shared organisation abstraction", status="Proposed", impl="PARTIAL",
         problem="Operator / CAMO / MRO / lessor roles.", choice="One Organization table, single org_type; OrganizationRole later.",
         alts="Table per role; boolean flags.", trade="Multi-role orgs pick one role.", risk="Onboarding of multi-role customers.",
         validate="Confirm with first CAMO/MRO customer.", evidence="models/organization.py"),
    dict(id="ADR-008", title="Engine as first-class assessable asset", status="Proposed", impl="VERIFY",
         problem="Engines carry their own AD stream.", choice="Engine as assessment subject (subject_type).",
         alts="Engine as component.", trade="Polymorphic subject.", risk="Evaluation uses aircraft_id/asset_id; engine subject not confirmed.",
         validate="Confirm engine-subject evaluations in tests.", evidence="api/v1/fleet_components.py (engine register)"),
    dict(id="ADR-009", title="Component / instance / installation split", status="Proposed", impl="PARTIAL",
         problem="Serialized vs lot parts; reinstall history.", choice="Three concepts.", alts="Four tables; single table.",
         trade="Joins.", risk="—", validate="Map to components + installation_history as built.", evidence="models/component.py, installation_history.py"),
    dict(id="ADR-010", title="Configuration as derived as-of view", status="Proposed", impl="PARTIAL",
         problem="'What configuration did the aircraft have then?'", choice="As-of query + immutable per-evaluation snapshot.",
         alts="Mutable current-config blob.", trade="Query cost.", risk="—", validate="Reproducibility test (re-derive snapshot).",
         evidence="applicability_evaluations.configuration_snapshot"),
]

# decisions this blueprint proposes (need owner approval)
PROPOSED_DECISIONS = [
    dict(id="ADR-011", title="PostgreSQL-native derived graph (supersedes ADR-003)",
         why="Matches the code; keeps one store; GraphRepository seam allows Neo4j later.",
         reverse="Traversal depth/fan-out makes SQL a measured bottleneck."),
    dict(id="ADR-012", title="Audit log + job table as the event backbone",
         why="Already transactional and immutable; add event_version, correlation_id, consumer cursor table.",
         reverse="Real-time fan-out to >3 independent consumers or cross-process push needed."),
    dict(id="ADR-013", title="Entitlement check on every execution path",
         why="REST, LISA, workers, listeners and schedulers call one resolver before acting.",
         reverse="—"),
    dict(id="ADR-014", title="LISA tool classes and write governance",
         why="read / draft / state-changing classes; state-changing tools require explicit human confirmation and are audited.",
         reverse="—"),
    dict(id="ADR-015", title="Edge time and durability contract",
         why="Gateway disk queue, gateway sequence number, measurement time from autopilot epoch; arrival time kept separately.",
         reverse="—"),
    dict(id="ADR-016", title="Sovereign / dedicated deployment profile",
         why="Single-tenant stack per sensitive customer using the same images; no shared AI provider unless approved.",
         reverse="Only if no defence customer is pursued."),
]

ROADMAP = [
    dict(n=1, title="Reliable automated telemetry acquisition", items=[
        "Durable edge queue + gateway sequence numbers (F4)", "Measurement-time contract for MAVLink (SYSTEM_TIME / GPS)",
        "Per-device machine credentials for push", "Physical bench: MAVLink over UDP/TCP via mavlink-router on a companion computer"],
        dep="—", gate="Bench report with loss / duplicate / latency figures"),
    dict(n=2, title="Unified entitlements & authorisation", items=[
        "Resolver call in workers, listeners, pollers (F3)", "Fix legacy mixed-suite default plan", "Suite boundary as data, not code"],
        dep="—", gate="Cancelled-tenant ingestion test fails closed"),
    dict(n=3, title="Tenant isolation & security", items=[
        "External penetration test", "Shared Redis rate limiter in multi-instance", "Secrets manager (replace env KOTA_SECRET_*)"],
        dep="2", gate="Pen-test findings closed"),
    dict(n=4, title="HUMS → M7 → LISA → maintenance traceability", items=[
        "Move signal sync to jobs (F6)", "Signal-type registry; retire /proactive (F7)", "Signal → work order link with outcome feedback"],
        dep="1", gate="One trace id from packet to closed work order"),
    dict(n=5, title="Compliance & evidence integrity", items=[
        "Rule versioning + effective dates (F8)", "ADR-005 decision lineage", "Object-lock / WORM bucket policy + checksum re-verify job"],
        dep="—", gate="Historical decision reproduced byte-for-byte"),
    dict(n=6, title="Production operations, monitoring & recovery", items=[
        "Python 3.12 pin + vitest in CI (F9)", "Prometheus scrape + alert rules", "Tested restore drill (measured RPO/RTO)"],
        dep="3", gate="Restore drill evidence"),
    dict(n=7, title="Bounded agentic workflows", items=[
        "Tool classes + persisted tool audit (F5)", "Draft-only work-order proposals with human confirmation", "Evaluation set of real operator questions"],
        dep="2, 4", gate="LISA eval pass rate agreed with operators"),
    dict(n=8, title="Advanced cross-asset & predictive intelligence", items=[
        "Outcome-labelled maintenance data", "Fleet-relative baselines", "Validated prognostic models per component class"],
        dep="4, 5, 7", gate="Model validated against confirmed removals"),
]

GLOSSARY = [
    ("AD", "Airworthiness Directive — mandatory regulatory requirement issued against a type certificate."),
    ("ADR", "Architecture Decision Record — documented decision with context, alternatives and consequences."),
    ("AOG", "Aircraft on Ground — asset unable to operate pending maintenance or parts."),
    ("Applicability", "Deterministic evaluation of whether a requirement applies to an asset configuration (TRUE / FALSE / UNKNOWN)."),
    ("Data source", "Tenant-bound configuration of one telemetry feed (connector type, mapping, health)."),
    ("Entitlement", "Commercial right to a feature, resolved from suite → plan → subscription → overrides → limits."),
    ("eVTOL / AAM", "Electric vertical take-off and landing / advanced air mobility."),
    ("Exceedance", "A reading or feature beyond a configured warning / critical limit or statistical threshold."),
    ("HUMS", "Health and Usage Monitoring System — health, usage, diagnostics, prognostics."),
    ("Kleene logic", "Three-valued logic where UNKNOWN is never silently treated as FALSE."),
    ("LISA", "Kota's grounded assistant — answers only from authorised tool results."),
    ("M4.2", "Fleet intelligence control center — presentation and decision summary over per-asset intelligence."),
    ("M7", "Proactive intelligence — canonical owner of actionable signals and their lifecycle."),
    ("M14-ext", "Cross-asset intelligence extension (H8.1) — descriptive fleet distributions. Not the M14 commercial milestone."),
    ("MAVLink", "Lightweight message protocol for drones and autopilots; a framing format, not a cloud endpoint."),
    ("MRO", "Maintenance, repair and overhaul."),
    ("Outbox", "Pattern where events are written in the same transaction as state, then published asynchronously."),
    ("RBAC", "Role-based access control (permissions per role, checked server-side)."),
    ("RII", "Required Inspection Item — independent inspection by a second qualified person."),
    ("RUL", "Remaining Useful Life — estimate, never a certified life limit."),
    ("Signal", "Persisted, actionable M7 record with severity, explanation trace and lifecycle."),
    ("SKIP LOCKED", "PostgreSQL row-locking mode letting parallel workers claim different jobs."),
    ("Suite", "Product family: Aircraft, Drone/UAV, Helicopter, eVTOL/AAM."),
    ("Tenant", "A customer organisation; every row carries organization_id."),
]
