"""H7: MRO + Compliance + Readiness Intelligence Integration — data model.

H7 is an INTEGRATION layer, not a new system of record. The only table this
module owns is MaintenanceIntelligenceCandidate — a lifecycle-managed
correlation/recommendation object surfaced when HUMS health/diagnostic/
prognostic signals converge with maintenance/inspection/compliance state.

It never duplicates data from the domains it correlates: source_lineage
stores {type, id, label} references only (see
app/services/mro_intelligence_service.py for the correlation logic that
populates it), never copies of the source records themselves.

H7 code must NEVER write to any authoritative domain table (Asset/Aircraft
lifecycle, ComplianceObligation.status, readiness_state fields,
HUMSDiagnosticCandidate, HUMSPrognosticRecord, WorkOrder). It only writes to
this table and to AuditEvent (see app/services/audit_service.py).
"""

import uuid
from datetime import datetime
from enum import StrEnum
from typing import Any

from sqlalchemy import DateTime, Float, ForeignKey, Index, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.db.base import Base, TenantScopedMixin, TimestampMixin, UUIDPKMixin


class MROCandidateType(StrEnum):
    """Small, purposeful set of convergent-signal categories.

    Kept deliberately narrow — new categories should only be added when an
    existing one genuinely does not fit, not for every new signal source.
    """

    INSPECTION_REVIEW = "INSPECTION_REVIEW"
    MAINTENANCE_ATTENTION = "MAINTENANCE_ATTENTION"
    COMPLIANCE_REVIEW = "COMPLIANCE_REVIEW"
    CONFLICT_REVIEW = "CONFLICT_REVIEW"


class MROCandidateStatus(StrEnum):
    OPEN = "OPEN"
    UNDER_REVIEW = "UNDER_REVIEW"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    DEFERRED = "DEFERRED"
    RESOLVED = "RESOLVED"


class MROCandidatePriority(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


# Status transitions this table permits. Used by mro_intelligence_service's
# lifecycle mutations to reject an invalid transition before it is written.
ALLOWED_CANDIDATE_TRANSITIONS: dict[str, set[str]] = {
    MROCandidateStatus.OPEN: {
        MROCandidateStatus.UNDER_REVIEW,
        MROCandidateStatus.ACCEPTED,
        MROCandidateStatus.REJECTED,
        MROCandidateStatus.DEFERRED,
        MROCandidateStatus.RESOLVED,
    },
    MROCandidateStatus.UNDER_REVIEW: {
        MROCandidateStatus.ACCEPTED,
        MROCandidateStatus.REJECTED,
        MROCandidateStatus.DEFERRED,
        MROCandidateStatus.RESOLVED,
    },
    MROCandidateStatus.DEFERRED: {
        MROCandidateStatus.UNDER_REVIEW,
        MROCandidateStatus.ACCEPTED,
        MROCandidateStatus.REJECTED,
        MROCandidateStatus.RESOLVED,
    },
    MROCandidateStatus.ACCEPTED: {MROCandidateStatus.RESOLVED},
    MROCandidateStatus.REJECTED: set(),
    MROCandidateStatus.RESOLVED: set(),
}


class MaintenanceIntelligenceCandidate(UUIDPKMixin, TenantScopedMixin, TimestampMixin, Base):
    """A correlated maintenance/compliance/readiness intelligence candidate.

    Distinct from ProactiveSignalRecord (app/models/proactive_signal.py):
    ProactiveSignalRecord is a transient, detector-driven alert; this table
    is a lifecycle-managed recommendation object requiring explicit human
    review/accept/reject/defer, generated by cross-domain correlation
    (health + diagnostic + prognostic + maintenance + compliance), never by
    a single-domain detector.

    source_lineage stores IDs/labels only — never copies of source-entity
    fields — so this row is always re-derivable from, and never drifts out
    of sync with, the authoritative systems it references.
    """

    __tablename__ = "mro_intelligence_candidates"
    __table_args__ = (
        Index("ix_mro_candidates_org_asset", "organization_id", "asset_id"),
        Index("ix_mro_candidates_org_status", "organization_id", "status"),
        Index("ix_mro_candidates_org_dedup_key", "organization_id", "dedup_key"),
    )

    asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("assets.id", ondelete="CASCADE"), nullable=False, index=True
    )
    component_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("components.id", ondelete="SET NULL"), nullable=True, index=True
    )

    candidate_type: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    status: Mapped[str] = mapped_column(
        String(16), nullable=False, default=MROCandidateStatus.OPEN, index=True
    )
    priority: Mapped[str] = mapped_column(String(16), nullable=False, default=MROCandidatePriority.MEDIUM)
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.5)

    reason: Mapped[str] = mapped_column(Text, nullable=False)

    # Idempotency/dedup key: derived deterministically from
    # asset_id + component_id + candidate_type + a stable hash of the
    # contributing source refs (see mro_intelligence_service._build_dedup_key).
    # Mirrors ProactiveSignalRecord.signal_key's "unique per org" pattern,
    # but is NOT globally unique here — a RESOLVED/REJECTED candidate may be
    # superseded by a new OPEN one sharing the same key once the underlying
    # signal set changes again.
    dedup_key: Mapped[str] = mapped_column(String(255), nullable=False, index=True)

    # [{type, id, label}, ...] — health/diagnostic/prognostic/maintenance/
    # inspection/compliance/evidence source references. IDs only, no copied
    # field data.
    source_lineage: Mapped[list[dict[str, Any]]] = mapped_column(JSONB, nullable=False, default=list)

    operational_impact: Mapped[str | None] = mapped_column(String(32), nullable=True)
    data_freshness: Mapped[str | None] = mapped_column(String(32), nullable=True)

    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    resolved_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    review_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )
