from fastapi import APIRouter

from app.api.v1 import (
    aerospace_intelligence,
    aircraft,
    airframes,
    aog,
    applicability,
    assessments,
    assets,
    auth,
    commercial_platform,
    compliance,
    control_center,
    data_import,
    billing,
    observability,
    data_sources,
    deferred_items,
    digital_twin,
    drones,
    live,
    device_gateway,
    edge_hardware,
    entitlements,
    evidence,
    facilities,
    fleet_components,
    findings,
    health,
    hums,
    hypercare,
    inspections,
    intelligence,
    inventory,
    lisa,
    maintenance,
    missions,
    mro_intelligence,
    part_requirements,
    parts,
    platform,
    proactive,
    procurement,
    product_catalog,
    purchase_orders,
    receiving,
    regulatory,
    release_readiness,
    sso,
    tat,
    technicians,
    telemetry,
    tenant,
    users,
    vendor_part_availability,
    vendors,
    warehouses,
    webhooks,
    work_orders,
)

api_router = APIRouter()
api_router.include_router(health.router)
api_router.include_router(auth.router)
api_router.include_router(aircraft.router)
api_router.include_router(assets.router)
api_router.include_router(facilities.router)
api_router.include_router(drones.router)
api_router.include_router(live.router)
api_router.include_router(airframes.helicopters_router)
api_router.include_router(fleet_components.router)
api_router.include_router(airframes.evtols_router)
api_router.include_router(missions.router)
api_router.include_router(aog.router)
api_router.include_router(work_orders.router)
api_router.include_router(evidence.router)
api_router.include_router(inspections.router)
api_router.include_router(findings.router)
api_router.include_router(tat.router)
api_router.include_router(release_readiness.router)
api_router.include_router(parts.router)
api_router.include_router(vendors.router)
api_router.include_router(part_requirements.router)
api_router.include_router(inventory.router)
api_router.include_router(vendor_part_availability.router)
api_router.include_router(procurement.router)
api_router.include_router(purchase_orders.router)
api_router.include_router(receiving.router)
api_router.include_router(maintenance.router)
api_router.include_router(deferred_items.router)
api_router.include_router(compliance.router)
api_router.include_router(applicability.router, prefix="/applicability")
api_router.include_router(regulatory.router)
api_router.include_router(control_center.router)
api_router.include_router(proactive.router)
api_router.include_router(intelligence.router)
api_router.include_router(warehouses.router)
api_router.include_router(technicians.router)
api_router.include_router(users.router)
api_router.include_router(lisa.router)
api_router.include_router(assessments.router)
api_router.include_router(platform.router)
api_router.include_router(product_catalog.router)
api_router.include_router(data_import.router)
api_router.include_router(entitlements.router)
api_router.include_router(tenant.router)
api_router.include_router(aerospace_intelligence.router)
api_router.include_router(hums.router)
api_router.include_router(telemetry.router)
api_router.include_router(telemetry.webhook_router)
api_router.include_router(sso.router)
api_router.include_router(hypercare.router)
api_router.include_router(digital_twin.router)
api_router.include_router(edge_hardware.router)
api_router.include_router(device_gateway.router)
api_router.include_router(commercial_platform.router)
api_router.include_router(mro_intelligence.router)
api_router.include_router(data_sources.router)
api_router.include_router(billing.router)
api_router.include_router(observability.router)
api_router.include_router(webhooks.router)
