"""M17: Canonical Telemetry Simulator for Independent Development & End-to-End Verification.

Provides deterministic simulation of canonical telemetry events across all operational,
degraded, anomaly, failure, and recovery scenarios without requiring a live UAV hardware connection.

Scenarios Supported:
1. NORMAL: Stable flight, healthy battery, nominal vibration (RMS ~1.8 mm/s), normal temperatures.
2. VIBRATION_DEGRADATION: Controlled rising vibration (from nominal -> elevated 5.5 mm/s -> critical 8.8 mm/s)
   with elevated kurtosis and crest factor to exercise fault signatures (bearing degradation, rotor imbalance).
3. TEMPERATURE_ANOMALY: Rising motor/ESC temperatures breaching warning thresholds.
4. BATTERY_DEGRADATION: Depleting voltage, rising internal resistance, high cycle counts.
5. TELEMETRY_STALENESS: Historical timestamp generation simulating telemetry gap / connection loss.
6. TELEMETRY_RECOVERY: Resumption of real-time telemetry stream after staleness.
7. SENSOR_ANOMALY: Single divergent sensor on a multi-sensor component.
8. FAILURE_HANDLING: Duplicate events, out-of-order packets, invalid measurements, degraded quality flags.
"""

from __future__ import annotations

import math
import random
import uuid
from datetime import UTC, datetime, timedelta
from typing import Any

from sqlalchemy.orm import Session

from app.models.asset import Asset
from app.models.hums import HUMSSensor
from app.schemas.telemetry import (
    NormalizedTelemetryEvent,
    TelemetryBatteryPayload,
    TelemetryFlightPayload,
    TelemetryIngestRequest,
    TelemetryIngestResponse,
    TelemetryReadingItem,
)
from app.services import telemetry_service


class TelemetryScenarioType:
    NORMAL = "NORMAL"
    VIBRATION_DEGRADATION = "VIBRATION_DEGRADATION"
    TEMPERATURE_ANOMALY = "TEMPERATURE_ANOMALY"
    BATTERY_DEGRADATION = "BATTERY_DEGRADATION"
    TELEMETRY_STALE = "TELEMETRY_STALE"
    TELEMETRY_RECOVERY = "TELEMETRY_RECOVERY"
    SENSOR_ANOMALY = "SENSOR_ANOMALY"
    DUPLICATE_EVENT = "DUPLICATE_EVENT"
    OUT_OF_ORDER = "OUT_OF_ORDER"


def generate_reading_burst(
    *,
    sensor_code: str,
    measurement_type: str,
    unit: str,
    base_value: float,
    noise_std: float = 0.1,
    sample_count: int = 20,
    component_id: uuid.UUID | None = None,
    data_quality: str = "VALID",
    kurtosis_spike: bool = False,
) -> list[TelemetryReadingItem]:
    """Generates a list of synthetic sensor readings with optional noise and impulsive spikes."""
    readings: list[TelemetryReadingItem] = []
    rng = random.Random(42)

    for i in range(sample_count):
        # Base gaussian variation
        val = base_value + rng.gauss(0.0, noise_std)
        # Add impulsive kurtosis spikes if requested (e.g. bearing fault signature)
        if kurtosis_spike and i % 5 == 0:
            val += base_value * 1.5

        val = max(0.0, round(val, 4))
        readings.append(
            TelemetryReadingItem(
                sensor_code=sensor_code,
                sensor_type="VIBRATION" if measurement_type == "vibration" else "TELEMETRY",
                measurement_type=measurement_type,
                value=val,
                unit=unit,
                component_id=component_id,
                data_quality=data_quality,
            )
        )
    return readings


def generate_canonical_event(
    *,
    source_asset_id: str,
    source_system: str = "KOTA_SIMULATOR",
    source_event_id: str | None = None,
    event_type: str = "REALTIME_TELEMETRY",
    event_timestamp: datetime | None = None,
    flight_number: str = "SIM-101",
    flight_duration_minutes: int = 20,
    battery_sn: str = "BAT-SIM-001",
    battery_voltage: float = 24.2,
    battery_health: int = 99,
    battery_cycles: int = 35,
    readings: list[TelemetryReadingItem] | None = None,
    raw_metadata: dict[str, Any] | None = None,
) -> NormalizedTelemetryEvent:
    """Constructs a single valid NormalizedTelemetryEvent conforming to the canonical boundary."""
    ts = event_timestamp or datetime.now(UTC)
    evt_id = source_event_id or f"sim-evt-{uuid.uuid4().hex[:12]}"

    flight_payload = TelemetryFlightPayload(
        flight_number=flight_number,
        duration_minutes=flight_duration_minutes,
        cycles=1,
        origin="SIM_BASE_A",
        destination="SIM_BASE_B",
        flown_at=ts - timedelta(minutes=flight_duration_minutes),
        notes="Generated by Canonical Telemetry Simulator",
    )

    battery_payload = TelemetryBatteryPayload(
        serial_number=battery_sn,
        cycle_count=battery_cycles,
        voltage_v=battery_voltage,
        internal_resistance_mohm=12.5,
        temperature_c=28.0,
        health_percent=battery_health,
    )

    return NormalizedTelemetryEvent(
        source_system=source_system,
        source_event_id=evt_id,
        source_asset_id=source_asset_id,
        event_type=event_type,
        event_timestamp=ts,
        flight=flight_payload,
        battery=battery_payload,
        readings=readings or [],
        raw_metadata=raw_metadata or {"simulated": True, "scenario": "CANONICAL_SIM"},
    )


def build_scenario_batch(
    scenario: str,
    *,
    source_asset_id: str,
    vib_sensor_code: str = "VIB_MAIN_ROTOR",
    temp_sensor_code: str = "TEMP_MOTOR_1",
    component_id: uuid.UUID | None = None,
    step: int = 1,
    base_time: datetime | None = None,
) -> NormalizedTelemetryEvent:
    """Builds a deterministic telemetry event for a given scenario step."""
    t0 = base_time or datetime.now(UTC)

    if scenario == TelemetryScenarioType.NORMAL:
        # Healthy nominal telemetry
        vib_readings = generate_reading_burst(
            sensor_code=vib_sensor_code,
            measurement_type="vibration",
            unit="mm/s",
            base_value=1.8,
            noise_std=0.1,
            sample_count=20,
            component_id=component_id,
        )
        temp_readings = generate_reading_burst(
            sensor_code=temp_sensor_code,
            measurement_type="temperature",
            unit="celsius",
            base_value=42.0,
            noise_std=0.5,
            sample_count=5,
            component_id=component_id,
        )
        return generate_canonical_event(
            source_asset_id=source_asset_id,
            source_event_id=f"sim-normal-step{step}-{t0.strftime('%H%M%S')}",
            event_timestamp=t0,
            battery_voltage=24.5,
            battery_health=99,
            readings=vib_readings + temp_readings,
            raw_metadata={"scenario": "NORMAL", "step": step},
        )

    elif scenario == TelemetryScenarioType.VIBRATION_DEGRADATION:
        # Step 1: Normal (~1.8 mm/s)
        # Step 2: Elevated (~5.6 mm/s with impulsive kurtosis spikes)
        # Step 3: Critical (~8.8 mm/s)
        if step <= 1:
            base_vib = 1.8
            kurtosis_spike = False
        elif step == 2:
            base_vib = 5.6
            kurtosis_spike = True
        else:
            base_vib = 8.8
            kurtosis_spike = True

        vib_readings = generate_reading_burst(
            sensor_code=vib_sensor_code,
            measurement_type="vibration",
            unit="mm/s",
            base_value=base_vib,
            noise_std=0.2,
            sample_count=20,
            component_id=component_id,
            kurtosis_spike=kurtosis_spike,
        )
        return generate_canonical_event(
            source_asset_id=source_asset_id,
            source_event_id=f"sim-vibdeg-step{step}-{t0.strftime('%H%M%S')}",
            event_timestamp=t0 + timedelta(minutes=step * 10),
            battery_voltage=23.8,
            battery_health=96,
            readings=vib_readings,
            raw_metadata={"scenario": "VIBRATION_DEGRADATION", "step": step, "base_vib": base_vib},
        )

    elif scenario == TelemetryScenarioType.TELEMETRY_STALE:
        # Event timestamp is 15 days in the past (exceeds default 7d warning and 14d critical)
        stale_time = t0 - timedelta(days=15)
        vib_readings = generate_reading_burst(
            sensor_code=vib_sensor_code,
            measurement_type="vibration",
            unit="mm/s",
            base_value=2.0,
            sample_count=20,
            component_id=component_id,
        )
        return generate_canonical_event(
            source_asset_id=source_asset_id,
            source_event_id=f"sim-stale-{uuid.uuid4().hex[:8]}",
            event_timestamp=stale_time,
            readings=vib_readings,
            raw_metadata={"scenario": "TELEMETRY_STALE"},
        )

    elif scenario == TelemetryScenarioType.TELEMETRY_RECOVERY:
        # Event timestamp is fresh (now)
        fresh_time = t0
        vib_readings = generate_reading_burst(
            sensor_code=vib_sensor_code,
            measurement_type="vibration",
            unit="mm/s",
            base_value=2.1,
            sample_count=20,
            component_id=component_id,
        )
        return generate_canonical_event(
            source_asset_id=source_asset_id,
            source_event_id=f"sim-recovery-{fresh_time.strftime('%H%M%S')}",
            event_timestamp=fresh_time,
            readings=vib_readings,
            raw_metadata={"scenario": "TELEMETRY_RECOVERY"},
        )

    elif scenario == TelemetryScenarioType.BATTERY_DEGRADATION:
        # High cycle count, degraded health and voltage
        return generate_canonical_event(
            source_asset_id=source_asset_id,
            source_event_id=f"sim-batdeg-{t0.strftime('%H%M%S')}",
            event_timestamp=t0,
            battery_voltage=20.5,
            battery_health=72,
            battery_cycles=310,
            readings=[],
            raw_metadata={"scenario": "BATTERY_DEGRADATION"},
        )

    else:
        # Default fallback
        return generate_canonical_event(
            source_asset_id=source_asset_id,
            event_timestamp=t0,
        )


def run_simulation_step(
    db: Session,
    *,
    organization_id: uuid.UUID,
    scenario: str,
    source_asset_id: str,
    vib_sensor_code: str = "VIB_MAIN_ROTOR",
    temp_sensor_code: str = "TEMP_MOTOR_1",
    component_id: uuid.UUID | None = None,
    step: int = 1,
    base_time: datetime | None = None,
) -> TelemetryIngestResponse:
    """Executes a simulation scenario step directly through the production ingestion boundary."""
    event = build_scenario_batch(
        scenario,
        source_asset_id=source_asset_id,
        vib_sensor_code=vib_sensor_code,
        temp_sensor_code=temp_sensor_code,
        component_id=component_id,
        step=step,
        base_time=base_time,
    )
    request = TelemetryIngestRequest(events=[event])
    response = telemetry_service.ingest_telemetry_batch(
        db, organization_id=organization_id, request=request
    )
    db.flush()
    return response


__all__ = [
    "TelemetryScenarioType",
    "generate_reading_burst",
    "generate_canonical_event",
    "build_scenario_batch",
    "run_simulation_step",
]
