"use client";

import Link from "next/link";
import { Breadcrumbs } from "@/components/layout/Breadcrumbs";
import { DataTable, type Column } from "@/components/tables/DataTable";
import { reportHistory, type ReportRecord } from "@/lib/mock/reports";

const columns: Column<ReportRecord>[] = [
  { key: "report", header: "Report", render: (r) => <span style={{ fontWeight: 600 }}>{r.title}</span>, sortValue: (r) => r.title },
  { key: "type", header: "Type", render: (r) => r.type.replace(/_/g, " "), sortValue: (r) => r.type },
  { key: "generatedBy", header: "Generated By", render: (r) => r.generatedBy, sortValue: (r) => r.generatedBy },
  { key: "scope", header: "Scope", render: (r) => r.scope, sortValue: (r) => r.scope },
  { key: "generatedDate", header: "Generated Date", render: (r) => r.generatedDate, sortValue: (r) => r.generatedDate },
  { key: "status", header: "Status", render: (r) => r.status },
  {
    key: "actions",
    header: "Actions",
    render: (r) => (
      <span className="ac-flex ac-gap-2">
        <Link href={`/reports/${r.id}`} className="ac-btn" style={{ padding: "4px 8px", fontSize: 12 }} onClick={(e) => e.stopPropagation()}>
          View
        </Link>
      </span>
    ),
  },
];

export default function ReportsPage() {
  return (
    <div>
      <Breadcrumbs items={[{ label: "Dashboard", href: "/dashboard" }, { label: "Reports" }]} />
      <div className="ac-section-header">
        <div>
          <h1 className="ac-h1">Reports</h1>
          <p className="ac-subtitle">
            Previously generated operations and compliance reports. Prototype only — reports are generated
            client-side from current demo data and are not backend-persisted.
          </p>
        </div>
      </div>
      <div className="ac-card" style={{ padding: 0 }}>
        <DataTable columns={columns} rows={reportHistory} getRowHref={(r) => `/reports/${r.id}`} />
      </div>
    </div>
  );
}
